source 'https://rubygems.org'
require 'rbconfig'
gem 'wdm', '~> 0.1.0' if RbConfig::CONFIG['target_os'] =~ /mswin|mingw/i
gem 'jekyll'
gem 'jekyll-assets'
gem 'maruku'
gem 'rake'
gem 'sass'
gem 'uglifier'
gem 'github-pages'
